// Platform-neutral key identity + the human-readable key-name vocabulary
// used by config.toml and the `configui` web page.
//
// Before the macOS port this role was played directly by the Win32
// `VIRTUAL_KEY` newtype (see the old vkname.rs): every keymap, config struct
// and held-key tracker stored raw VK codes, and the name<->VK tables lived
// in two parallel arrays. That works on exactly one OS. `Key` is the same
// closed vocabulary — deliberately NOT "any code the user types", so every
// name that round-trips through here either produces a real, intentional
// key or a caught error, never a silently wrong/unmapped value — expressed
// as a plain enum, with each variant's per-OS code carried alongside it in
// ONE table (KEY_DEFS, generated by the `define_keys!` macro below from a
// single list) so the name, the Windows VK and the macOS virtual keycode
// can never drift apart.
//
// `all_key_names()` remains the single source of truth for what
// configui.html's <select> options are allowed to contain (fetched from the
// running driver via GET /api/key-options rather than duplicated in the
// HTML, so the two can never drift apart) — now filtered to the keys the
// CURRENT OS can actually emit (see `Key::supported_here`).

/// What a `Key` becomes on macOS: a CoreGraphics virtual keycode
/// (`kVK_*`, posted via CGEventPost), an `NX_KEYTYPE_*` "system-defined"
/// media key (posted via NSEvent), or nothing at all — macOS has no
/// equivalent for a handful of Windows VKs (F21-F24, MEDIA_STOP).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum MacKey {
    Code(u16),
    Media(u8),
    Unsupported,
}

pub struct KeyDef {
    pub key: Key,
    pub name: &'static str,
    /// Win32 virtual-key code (`VK_*`). Stored as the raw u16 rather than
    /// the `windows` crate's `VIRTUAL_KEY` so this table compiles on every
    /// OS; platform/windows.rs wraps it back into `VIRTUAL_KEY` at the
    /// SendInput call site.
    pub win_vk: u16,
    pub mac: MacKey,
}

// One row per key: `Variant => "NAME", win: VK, mac: MacKey;`. Rows are in
// configui display order within each group (see `key_names_grouped`), so
// reordering rows here reorders the web page's dropdowns.
macro_rules! define_keys {
    ($( $variant:ident => $name:literal, win: $vk:expr, mac: $mac:expr; )*) => {
        #[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
        pub enum Key {
            $( $variant, )*
        }

        pub const KEY_DEFS: &[KeyDef] = &[
            $( KeyDef { key: Key::$variant, name: $name, win_vk: $vk, mac: $mac }, )*
        ];
    };
}

use MacKey::{Code, Media, Unsupported};

// NX_KEYTYPE_* values (IOKit/hidsystem/ev_keymap.h) for the macOS
// "system-defined" media/volume events.
const NX_KEYTYPE_SOUND_UP: u8 = 0;
const NX_KEYTYPE_SOUND_DOWN: u8 = 1;
const NX_KEYTYPE_MUTE: u8 = 7;
const NX_KEYTYPE_PLAY: u8 = 16;
const NX_KEYTYPE_NEXT: u8 = 17;
const NX_KEYTYPE_PREVIOUS: u8 = 18;

define_keys! {
    // --- digits (Windows VK == ASCII; macOS kVK_ANSI_* are NOT contiguous) ---
    Digit0 => "0", win: 0x30, mac: Code(0x1D);
    Digit1 => "1", win: 0x31, mac: Code(0x12);
    Digit2 => "2", win: 0x32, mac: Code(0x13);
    Digit3 => "3", win: 0x33, mac: Code(0x14);
    Digit4 => "4", win: 0x34, mac: Code(0x15);
    Digit5 => "5", win: 0x35, mac: Code(0x17);
    Digit6 => "6", win: 0x36, mac: Code(0x16);
    Digit7 => "7", win: 0x37, mac: Code(0x1A);
    Digit8 => "8", win: 0x38, mac: Code(0x1C);
    Digit9 => "9", win: 0x39, mac: Code(0x19);
    // --- letters ---
    A => "A", win: 0x41, mac: Code(0x00);
    B => "B", win: 0x42, mac: Code(0x0B);
    C => "C", win: 0x43, mac: Code(0x08);
    D => "D", win: 0x44, mac: Code(0x02);
    E => "E", win: 0x45, mac: Code(0x0E);
    F => "F", win: 0x46, mac: Code(0x03);
    G => "G", win: 0x47, mac: Code(0x05);
    H => "H", win: 0x48, mac: Code(0x04);
    I => "I", win: 0x49, mac: Code(0x22);
    J => "J", win: 0x4A, mac: Code(0x26);
    K => "K", win: 0x4B, mac: Code(0x28);
    L => "L", win: 0x4C, mac: Code(0x25);
    M => "M", win: 0x4D, mac: Code(0x2E);
    N => "N", win: 0x4E, mac: Code(0x2D);
    O => "O", win: 0x4F, mac: Code(0x1F);
    P => "P", win: 0x50, mac: Code(0x23);
    Q => "Q", win: 0x51, mac: Code(0x0C);
    R => "R", win: 0x52, mac: Code(0x0F);
    S => "S", win: 0x53, mac: Code(0x01);
    T => "T", win: 0x54, mac: Code(0x11);
    U => "U", win: 0x55, mac: Code(0x20);
    V => "V", win: 0x56, mac: Code(0x09);
    W => "W", win: 0x57, mac: Code(0x0D);
    X => "X", win: 0x58, mac: Code(0x07);
    Y => "Y", win: 0x59, mac: Code(0x10);
    Z => "Z", win: 0x5A, mac: Code(0x06);
    // --- function keys (VK_F1 = 0x70 .. VK_F24 = 0x87) ---
    F1 => "F1", win: 0x70, mac: Code(0x7A);
    F2 => "F2", win: 0x71, mac: Code(0x78);
    F3 => "F3", win: 0x72, mac: Code(0x63);
    F4 => "F4", win: 0x73, mac: Code(0x76);
    F5 => "F5", win: 0x74, mac: Code(0x60);
    F6 => "F6", win: 0x75, mac: Code(0x61);
    F7 => "F7", win: 0x76, mac: Code(0x62);
    F8 => "F8", win: 0x77, mac: Code(0x64);
    F9 => "F9", win: 0x78, mac: Code(0x65);
    F10 => "F10", win: 0x79, mac: Code(0x6D);
    F11 => "F11", win: 0x7A, mac: Code(0x67);
    F12 => "F12", win: 0x7B, mac: Code(0x6F);
    F13 => "F13", win: 0x7C, mac: Code(0x69);
    F14 => "F14", win: 0x7D, mac: Code(0x6B);
    F15 => "F15", win: 0x7E, mac: Code(0x71);
    F16 => "F16", win: 0x7F, mac: Code(0x6A);
    F17 => "F17", win: 0x80, mac: Code(0x40);
    F18 => "F18", win: 0x81, mac: Code(0x4F);
    F19 => "F19", win: 0x82, mac: Code(0x50);
    F20 => "F20", win: 0x83, mac: Code(0x5A);
    F21 => "F21", win: 0x84, mac: Unsupported;
    F22 => "F22", win: 0x85, mac: Unsupported;
    F23 => "F23", win: 0x86, mac: Unsupported;
    F24 => "F24", win: 0x87, mac: Unsupported;
    // --- named specials (the old vkname.rs KEY_TABLE, same order) ---
    Left => "LEFT", win: 0x25, mac: Code(0x7B);
    Up => "UP", win: 0x26, mac: Code(0x7E);
    Right => "RIGHT", win: 0x27, mac: Code(0x7C);
    Down => "DOWN", win: 0x28, mac: Code(0x7D);
    Space => "SPACE", win: 0x20, mac: Code(0x31);
    Enter => "ENTER", win: 0x0D, mac: Code(0x24);
    Tab => "TAB", win: 0x09, mac: Code(0x30);
    Escape => "ESCAPE", win: 0x1B, mac: Code(0x35);
    // macOS "Delete" (kVK_Delete) is the PC Backspace key; PC Delete is
    // kVK_ForwardDelete.
    Backspace => "BACKSPACE", win: 0x08, mac: Code(0x33);
    LShift => "LSHIFT", win: 0xA0, mac: Code(0x38);
    RShift => "RSHIFT", win: 0xA1, mac: Code(0x3C);
    LCtrl => "LCTRL", win: 0xA2, mac: Code(0x3B);
    RCtrl => "RCTRL", win: 0xA3, mac: Code(0x3E);
    // LALT/RALT are the macOS Option keys.
    LAlt => "LALT", win: 0xA4, mac: Code(0x3A);
    RAlt => "RALT", win: 0xA5, mac: Code(0x3D);
    // New with the macOS port: Command on macOS, the Windows (Win) key on
    // Windows (VK_LWIN/VK_RWIN).
    LCmd => "LCMD", win: 0x5B, mac: Code(0x37);
    RCmd => "RCMD", win: 0x5C, mac: Code(0x36);
    Home => "HOME", win: 0x24, mac: Code(0x73);
    End => "END", win: 0x23, mac: Code(0x77);
    PageUp => "PAGEUP", win: 0x21, mac: Code(0x74);
    PageDown => "PAGEDOWN", win: 0x22, mac: Code(0x79);
    // A PC keyboard's Insert key reaches macOS as kVK_Help.
    Insert => "INSERT", win: 0x2D, mac: Code(0x72);
    Delete => "DELETE", win: 0x2E, mac: Code(0x75);
    // --- media / volume (the old MEDIA_KEY_TABLE; configui's own category) ---
    MediaPlayPause => "MEDIA_PLAY_PAUSE", win: 0xB3, mac: Media(NX_KEYTYPE_PLAY);
    MediaStop => "MEDIA_STOP", win: 0xB2, mac: Unsupported;
    MediaNext => "MEDIA_NEXT", win: 0xB0, mac: Media(NX_KEYTYPE_NEXT);
    MediaPrev => "MEDIA_PREV", win: 0xB1, mac: Media(NX_KEYTYPE_PREVIOUS);
    VolumeMute => "VOLUME_MUTE", win: 0xAD, mac: Media(NX_KEYTYPE_MUTE);
    VolumeDown => "VOLUME_DOWN", win: 0xAE, mac: Media(NX_KEYTYPE_SOUND_DOWN);
    VolumeUp => "VOLUME_UP", win: 0xAF, mac: Media(NX_KEYTYPE_SOUND_UP);
}

impl Key {
    fn def(self) -> &'static KeyDef {
        // KEY_DEFS is generated from the same list as the enum, in the same
        // order, so the variant's discriminant is its row index.
        &KEY_DEFS[self as usize]
    }

    /// The config.toml / configui name for this key (e.g. "LSHIFT").
    pub fn name(self) -> &'static str {
        self.def().name
    }

    /// Win32 virtual-key code (`VK_*`).
    #[cfg_attr(not(windows), allow(dead_code))]
    pub fn win_vk(self) -> u16 {
        self.def().win_vk
    }

    /// macOS keycode / media-key mapping.
    #[cfg_attr(not(target_os = "macos"), allow(dead_code))]
    pub fn mac(self) -> MacKey {
        self.def().mac
    }

    /// Whether the OS this binary was built for can emit this key at all.
    /// Windows can emit the whole vocabulary; macOS has no equivalent for a
    /// few (see `MacKey::Unsupported` rows above).
    pub fn supported_here(self) -> bool {
        if cfg!(target_os = "macos") {
            self.mac() != Unsupported
        } else {
            true
        }
    }

    pub fn is_media(self) -> bool {
        matches!(self, Key::MediaPlayPause | Key::MediaStop | Key::MediaNext | Key::MediaPrev
            | Key::VolumeMute | Key::VolumeDown | Key::VolumeUp)
    }

    /// Looks a name up (case-insensitive, surrounding whitespace ignored)
    /// regardless of whether the current OS can emit it. Use `from_name`
    /// for config parsing; this exists so callers can tell "unknown name"
    /// apart from "known key, unavailable on this OS" in their warnings.
    pub fn lookup(name: &str) -> Option<Key> {
        let upper = name.trim().to_ascii_uppercase();
        KEY_DEFS.iter().find(|d| d.name == upper).map(|d| d.key)
    }

    /// Parses a human-readable key name (case-insensitive) into a `Key`,
    /// accepting only keys the current OS can emit. Returns None for
    /// anything else — the caller is expected to fall back / reject, never
    /// to guess.
    pub fn from_name(name: &str) -> Option<Key> {
        Key::lookup(name).filter(|k| k.supported_here())
    }
}

/// Every name `Key::from_name` accepts (on this OS), in display order —
/// the "basic" category only, i.e. everything except the media keys.
/// Populates configui.html's dropdowns via GET /api/key-options.
pub fn all_key_names() -> Vec<String> {
    KEY_DEFS
        .iter()
        .filter(|d| !d.key.is_media() && d.key.supported_here())
        .map(|d| d.name.to_string())
        .collect()
}

/// (basic names, media names) — the same vocabulary as all_key_names(),
/// just split into the two categories configui.html's key picker offers.
/// Used by configui.rs's GET /api/key-options.
pub fn key_names_grouped() -> (Vec<String>, Vec<String>) {
    let media = KEY_DEFS
        .iter()
        .filter(|d| d.key.is_media() && d.key.supported_here())
        .map(|d| d.name.to_string())
        .collect();
    (all_key_names(), media)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_index_matches_enum_discriminant() {
        for (i, d) in KEY_DEFS.iter().enumerate() {
            assert_eq!(d.key as usize, i, "{} is out of order", d.name);
            assert_eq!(d.key.name(), d.name);
        }
    }

    #[test]
    fn names_and_codes_are_unique() {
        for (i, a) in KEY_DEFS.iter().enumerate() {
            for b in &KEY_DEFS[i + 1..] {
                assert_ne!(a.name, b.name);
                assert_ne!(a.win_vk, b.win_vk, "{} and {} share a VK", a.name, b.name);
                if a.mac != Unsupported {
                    assert_ne!(a.mac, b.mac, "{} and {} share a mac code", a.name, b.name);
                }
            }
        }
    }

    #[test]
    fn digits_and_letters_round_trip() {
        for c in ('0'..='9').chain('A'..='Z') {
            let key = Key::from_name(&c.to_string()).unwrap();
            assert_eq!(key.name(), c.to_string());
            // Windows VK for digits/letters is the ASCII code.
            assert_eq!(key.win_vk(), c as u16);
        }
    }

    #[test]
    fn function_keys_round_trip_and_are_bounded() {
        for n in 1..=24 {
            let name = format!("F{n}");
            let key = Key::lookup(&name).unwrap();
            assert_eq!(key.name(), name);
            assert_eq!(key.win_vk(), 0x70 + n - 1);
        }
        assert_eq!(Key::from_name("F0"), None);
        assert_eq!(Key::from_name("F25"), None);
    }

    #[test]
    fn every_supported_name_round_trips() {
        let (basic, media) = key_names_grouped();
        assert!(basic.len() > 50);
        for name in basic.iter().chain(&media) {
            let key = Key::from_name(name).unwrap_or_else(|| panic!("{name} did not round-trip"));
            assert_eq!(key.name(), name);
        }
        for name in &media {
            assert!(!basic.contains(name));
        }
    }

    #[test]
    fn case_insensitive_and_unknown_names_rejected() {
        assert_eq!(Key::from_name("left"), Some(Key::Left));
        assert_eq!(Key::from_name(" f1 "), Key::from_name("F1"));
        assert_eq!(Key::from_name("NOT_A_KEY"), None);
        assert_eq!(Key::from_name(""), None);
    }

    #[test]
    fn unsupported_keys_are_known_but_rejected_on_macos() {
        // Known everywhere...
        assert_eq!(Key::lookup("F24"), Some(Key::F24));
        assert_eq!(Key::lookup("MEDIA_STOP"), Some(Key::MediaStop));
        // ...but only emittable where the OS has a code for them.
        let expect = !cfg!(target_os = "macos");
        assert_eq!(Key::from_name("F24").is_some(), expect);
        assert_eq!(Key::from_name("MEDIA_STOP").is_some(), expect);
        assert_eq!(all_key_names().contains(&"F24".to_string()), expect);
    }

    // The raw VK numbers in KEY_DEFS must agree with the `windows` crate's
    // own constants — this is the one place the table can be checked
    // against the real SDK header values.
    #[cfg(windows)]
    #[test]
    fn win_vk_table_matches_windows_crate_constants() {
        use windows::Win32::UI::Input::KeyboardAndMouse::*;
        let expect: &[(Key, VIRTUAL_KEY)] = &[
            (Key::Digit0, VK_0),
            (Key::A, VK_A),
            (Key::F1, VK_F1),
            (Key::F24, VK_F24),
            (Key::Left, VK_LEFT),
            (Key::Up, VK_UP),
            (Key::Right, VK_RIGHT),
            (Key::Down, VK_DOWN),
            (Key::Space, VK_SPACE),
            (Key::Enter, VK_RETURN),
            (Key::Tab, VK_TAB),
            (Key::Escape, VK_ESCAPE),
            (Key::Backspace, VK_BACK),
            (Key::LShift, VK_LSHIFT),
            (Key::RShift, VK_RSHIFT),
            (Key::LCtrl, VK_LCONTROL),
            (Key::RCtrl, VK_RCONTROL),
            (Key::LAlt, VK_LMENU),
            (Key::RAlt, VK_RMENU),
            (Key::LCmd, VK_LWIN),
            (Key::RCmd, VK_RWIN),
            (Key::Home, VK_HOME),
            (Key::End, VK_END),
            (Key::PageUp, VK_PRIOR),
            (Key::PageDown, VK_NEXT),
            (Key::Insert, VK_INSERT),
            (Key::Delete, VK_DELETE),
            (Key::MediaPlayPause, VK_MEDIA_PLAY_PAUSE),
            (Key::MediaStop, VK_MEDIA_STOP),
            (Key::MediaNext, VK_MEDIA_NEXT_TRACK),
            (Key::MediaPrev, VK_MEDIA_PREV_TRACK),
            (Key::VolumeMute, VK_VOLUME_MUTE),
            (Key::VolumeDown, VK_VOLUME_DOWN),
            (Key::VolumeUp, VK_VOLUME_UP),
        ];
        for (key, vk) in expect {
            assert_eq!(key.win_vk(), vk.0, "{}", key.name());
        }
    }
}
